version: 2
updates:
  # npm package dependencies (package.json)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  # Docker base images (Dockerfile)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  # GitHub Actions versions (.github/workflows)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
