version: '3.8'

services:
  # 1. service: Node.js app
  node-app:
    build: .   # use dockerfile in current dir
    ports: 
      - "127.0.0.1:3000:3000" # connect with port 3000 to localhost
    environment:
      - MONGO_URI=${MONGO_URI}
    depends_on:
      mongodb: # nodejs app will run after mongodb
        condition: service_healthy
    networks:
      - app-network # include this service to shared network

  # 2. service: MongoDB
  mongodb:
    image: mongo:6.0 # official image from docker hub
    # ports: - "27017:27017" -> Don't open ports to outside
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db # we connect volumes to store the data after container is deleted.
    networks:
      - app-network # add db to shared network

# health check to verify mongodb is ready to prevent hanging node requests
# needed to fix ci workflow issues in mongoose 9+
    healthcheck:
      test: ["CMD", "mongosh", "-u", "${MONGO_INITDB_ROOT_USERNAME}", "-p", "${MONGO_INITDB_ROOT_PASSWORD}", "--authenticationDatabase", "admin", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

# define shared network
networks:
  app-network:
    driver: bridge

# Volume (Permanent Storage)
volumes:
  mongo-data: